### ISSUE TITLE
Doesn't work with gmail signatures

### ISSUE THREAD

**Issue by runekaagaard** [alpha22jp/atomic-chrome#10]
Hi, im writing this in emacs btw :) When I'm composing an email in gmail, my signature gets turned into something like:

    <font face="courier new, monospace">Best,</font>
    <font face="courier new, monospace">Rune Kaagaard</font>
    ...

Is there a fix for that?

**Comment by alpha22jp** [comment]
Hi @runekaagaard 

I can replicate the problem. It seems to be an issue of Chrome extension, because the same problem occurs even when I use Atom instead of Emacs. Could you raise a issue on [Atomic Chrome](https://github.com/tuvistavie/atomic-chrome) if you want to have this problem fixed?

**Comment by runekaagaard** [comment]
Thx, found the issue here: https://github.com/tuvistavie/atomic-chrome-atom/issues/8

**Comment by alpha22jp** [comment]
@runekaagaard,

I just released the new version which supports [Ghost Text](https://github.com/GhostText/GhostText) as browser extension. Ghost Text is better than Atomic Chrome for handling contentEditable area like Gmail. Please try it out.

**Comment by runekaagaard** [comment]
Hi thats super cool, will try it out!

**Comment by runekaagaard** [comment]
Hi again

OK, that was both better and worse :) The signature didn't get html encoded in gmail, but I have to edit the document in html, not plain text.

I've added a `sig` yasnippet, that I can use to insert the signature when using the Atomic Chrome option. Thats a fine workaround.
