### ISSUE TITLE
enable flyspell-mode when opening the edit window

### ISSUE THREAD

**Issue by zeltak** [alpha22jp/atomic-chrome#14]
Hi

first of all a Huge thx! i really enjoy using atomic-chrome each day!

a small Question: is it possible to have an option to enable flyspell-mode when opening the edit window? right now i need to do it manually each time

best

Z

**Comment by alpha22jp** [comment]
Hi @zeltak 

You can use `atomic-chrome-edit-mode-hook` like below for that.

``` emacs-lisp
(add-hook 'atomic-chrome-edit-mode-hook 'flyspell-mode)
```

**Comment by zeltak** [comment]
thx its perfect!
