### ISSUE TITLE
What port should I bind to GhostText's settings?

### ISSUE THREAD

**Issue by cmal** [alpha22jp/atomic-chrome#20]
Hi, I use GhostText. I find this atomic-chrome try to use http port 4001 to transmit data.
So I try to bind GhostText's port to 4001 in GhostText's settings.
But I found the GhostText can not invoke emacs buffer.

I used `(atomic-chrome-start-server)` in Emacs. 
Then I used `lsof` to find that Emacs was listening on 4001.

>  lsof -i tcp:4001  
> COMMAND     PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> Emacs-x86 45451 yuzhao   12u  IPv4 0x1087ba5a5c2a938b      0t0  TCP localhost:newoak (LISTEN)

Is this because I bind the GhostText to a wrong port?
Thanks!

**Comment by alpha22jp** [comment]
@cmal 

I use GhostText with TCP port 4001 (default setting of GhostText) too, and it's working well. I'm not sure why it doesn't work for you.

**Comment by cmal** [comment]
I don't know why, but it works now. Thanks.
