### ISSUE TITLE
New lines (hard returns) not passed to browser when using GhostText plugin

### ISSUE THREAD

**Issue by singletS** [alpha22jp/atomic-chrome#23]
Thanks for contributing this useful tool.
I have used the Atomic Chrome plugin with no problems.
Trying GhostText there is a problem entering hard returns; these are not recognized in the text area, so everything is on a single line, despite new lines appearing in the emacs buffer.

Actually, the motivation for trying GhostText was to find a way to export org-mode markup to markdown (or html) before it's sent to the browser text area. This is my ultimate goal...can this be done with (or added to) atomic-chrome?
Thanks again for your work.
emacs-version: GNU Emacs 26.0.50

**Comment by alpha22jp** [comment]
@singletS

I'm now using atomic-chrome.el with GhostText plugin to write this text. And there is no problem with inputing hard returns. I guess the problem depends on your settings or environment.

**Comment by singletS** [comment]
What is your environment?  Maybe I can figure out what's causing the problem in mine:  spacemacs 0.200.9; emacs 26.0.50 linux, chromium 58 linux

**Comment by alpha22jp** [comment]
@singletS 

My environmnt is Emacs 25.1 and Chrome 58 on Windows/Linux.

**Comment by singletS** [comment]
I think I understand what's happening.  I was using GhostText to edit a gmail contentEditable area. GhostText sends the emacs input immediately, but the gmail window accepts this as *html* only. So no new lines are not rendered until a `</br>` or `</p>` or other "line breaking" html markup is entered in the emacs buffer. Using GhostText to edit a github issue textarea (which isn't assuming html), newlines work just fine.

The Atomic Chrome plugin must work a bit differently; emacs buffer contents are sent to the gmail window, yet the new lines are respected.

So, I guess my "issue" isn't an issue but rather a feature request/design question: would it be possible to have atomic-chrome.el wait for an explicit command before sending the stream to GhostText (or Atomic Chrome)?  A user could then use whatever markup is desired (markdown, org-mode) so long as it's converted to the format the textarea is capable of accepting, such as html, plaintext, etc.  This is how ham-mode and gmm used to work with It's all Text (broken now). This approach would mess up two-way editing and instant rendering, tho.

Again, thanks for the info and your work on this.
