### ISSUE TITLE
silently failing when blocked by uMatrix

### ISSUE THREAD

**Issue by anarcat** [alpha22jp/atomic-chrome#27]
Hi,

I'm trying to see how to make this work in my setup, as a replacement for the obsolete [It's all text](https://github.com/docwhat/itsalltext/). I have installed the extension from the [Mozilla add-ons site](https://addons.mozilla.org/en-US/firefox/addon/ghosttext/) (version GhostText 17.6.1.407) and I have installed the Emacs extension as well (atomic-chrome 20161213.730). I'm using GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian, in Debian stretch.

I have also tested the "atomic chrome" extension in Chrome itself, to no avail: nothing happens on the Emacs side at all. I can confirm port 4001 is open on Emacs' side and that the same port is configured in the Firefox extension:

```
[998]anarcat@curie:anarc.at$ lsof -i tcp:4001
COMMAND   PID    USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
emacs   32395 anarcat   15u  IPv4 7026340      0t0  TCP localhost:4001 (LISTEN)
```

Nothing in the *Messages* buffer and no traffic flowing on port 4001 according to tcpdump. When I disable the uMatrix extension, traffic flows however, so it seems that local XHR requests are blocked by uMatrix. On fixing that, the extension mostly works.

It would be nice if GhostText would notice it cannot send XHR requests because of some block and pop an error message instead of just silently failing. It doesn't say anything in the Javascript console either.

**Comment by alpha22jp** [comment]
Hi @anarcat 

Sorry, this extension doesn't support Firefox as a browser. Since I don't use Firefox, I'm not willing to make it work with Firefox. But I'd appreciate if you make a patch to fix the problem.

**Comment by anarcat** [comment]
hi.

i obviously filed this against the wrong project - apologies. this belongs to the GhostText project.
