### ISSUE TITLE
Configurable Port

### ISSUE THREAD

**Issue by Stebalien** [alpha22jp/atomic-chrome#29]
Please consider making the port(s) configurable. I use another application (IPFS) that listens on port 4001 by default.

**Comment by sphakka** [comment]
This doesn't seem to work on Emacs-26.1 (+ FireFox Quantum 64.0 and latest GhostText):

`(setq atomic-chrome-server-ghost-text-port 4441)`

nmap says the port is closed...

**Comment by alpha22jp** [comment]
@sphakka 

> This doesn't seem to work on Emacs-26.1 (+ FireFox Quantum 64.0 and latest GhostText):
> 
> `(setq atomic-chrome-server-ghost-text-port 4441)`
> 
> nmap says the port is closed...

Did you set the same port in ghost-text extension setting as below?

![ghosttext](https://user-images.githubusercontent.com/6090562/53822385-f6de4080-3fb2-11e9-9a37-77be1c6b6dec.png)

**Comment by sphakka** [comment]
Sure ^_^

**Comment by alpha22jp** [comment]
@sphakka

In that case, i'm not sure why it doesn't work for you. It's working in my environment. Do you set `atomic-chrome-server-ghost-text-port` before you call `atomic-chrome-start-server`?

**Comment by sphakka** [comment]
Ha, ha stupid me! Indeed that setting wasn't in the right place. BTW, it looks like the atomic server is not restarted when eval'ing my `.emacs` buffer (that also contributed to my confusion): I have to stop and start it again... Thanks for helping :-)
