### ISSUE TITLE
Customization Examples

### ISSUE THREAD

**Issue by mankoff** [alpha22jp/atomic-chrome#3]
Can you provide an example of customizing a major mode for a particular website?

**Comment by alpha22jp** [comment]
Hi @mankoff,

You can use the customize variable `atomic-chrome-default-major-mode` to set the major mode for editing buffer. But there is no way to choose major mode depending on web site. Please refer to #1 for the reason.

**Comment by alpha22jp** [comment]
Hi @mankoff,

I sent PR to Atomic Chrome browser extension which makes the editor to know the page URL, and it was just accepted.

Please update the browser extension and this elisp to the latest version. Now you can customize the major mode for a paticular website with `atomic-chrome-url-major-mode-alist`. I also added an exmaple for that to README.md.

**Comment by mankoff** [comment]
Wow. Quick improvement and it works great. Thanks!

**Comment by joostkremers** [comment]
This is great, thanks!
