### ISSUE TITLE
Have atomic-chrome avoid losing unsaved buffer contents on C-c C-c

### ISSUE THREAD

**Issue by stevevdvkpe** [alpha22jp/atomic-chrome#37]
Because so many other things in Emacs tend to automatically complete with C-c C-c I have been annoying myself because I set atomic-chrome-enable-auto-update to nil but forget to sync the buffer contents with C-x C-s before closing the atomic-chrome buffer with C-c C-c.  Here is a simple patch that clears the buffer-modified flag whenever atomic-chrome-send-buffer-text is run to sync the buffer to the browser edit area, and has atomic-chrome-close-current-buffer prompt the user if buffer-modified-p is true to confirm closing the buffer if it is unsynced.  This also works when atomic-chrome-enable-auto-update is set since in that case atomic-chrome-send-buffer-text is run after every command.

```
--- atomic-chrome.el.orig	2017-12-06 14:02:30.177761463 -0800
+++ atomic-chrome.el	2018-03-21 11:51:02.778380418 -0700
@@ -155,7 +155,8 @@
         (if (eq (websocket-server-conn socket) atomic-chrome-server-ghost-text)
             (list (cons "text" text))
           (list '("type" . "updateText")
-                (cons "payload" (list (cons "text" text))))))))))
+                (cons "payload" (list (cons "text" text))))))))
+    (set-buffer-modified-p nil)))
 
 (defun atomic-chrome-set-major-mode (url)
   "Set major mode for editing buffer depending on URL.
@@ -216,7 +217,9 @@
 (defun atomic-chrome-close-current-buffer ()
   "Close current buffer and connection from client."
   (interactive)
-  (atomic-chrome-close-edit-buffer (current-buffer)))
+  (when (or (not (buffer-modified-p))
+	    (yes-or-no-p "Buffer has not been saved, close anyway? "))
+    (atomic-chrome-close-edit-buffer (current-buffer))))
 
 (defun atomic-chrome-update-buffer (socket text)
   "Update text on buffer associated with SOCKET to TEXT."
```

**Comment by alpha22jp** [comment]
@stevevdvkpe 

Thank you for reporting this issue. I merged your patch.

**Comment by stevevdvkpe** [comment]
Does this help?  This clears buffer-modified-p when a buffer is first created and the text from the textarea is inserted.

--- atomic-chrome.el~	2018-03-21 14:50:29.200615891 -0700
+++ atomic-chrome.el	2018-07-05 11:42:36.852943451 -0700
@@ -201,7 +201,8 @@
              (list socket (atomic-chrome-show-edit-buffer buffer title))
              atomic-chrome-buffer-table)
       (atomic-chrome-set-major-mode url)
-      (insert text))))
+      (insert text)
+      (set-buffer-modified-p nil))))
 
 (defun atomic-chrome-close-edit-buffer (buffer)
   "Close buffer BUFFER if it's one of Atomic Chrome edit buffers."
