### ISSUE TITLE
Launch Atomic Chrome extension with shortcut key?

### ISSUE THREAD

**Issue by ReneFroger** [alpha22jp/atomic-chrome#44]
I like Atomic-Chrome for Emacs very much, your work in this is appreciated.

However, there is still one thing that I miss greatly. Like in [Emacs-Anywhere extension](https://github.com/zachcurry/emacs-anywhere) you can launch it with a hotkey.
 I need to use my mouse everytime, when I wanted to launch the Atomic Chrome. It's counter-inuitively of Emacs' philosophy, if I might say, where you could do everything with the keyboard. Many Chrome extensions support the launch feature with a hotkey only.

Why couldn't Atomic Chrome to do the same if I might say?

**Comment by alpha22jp** [comment]
@ReneFroger 

> Why couldn't Atomic Chrome to do the same if I might say?

Because operations to launch Atomic Chrome depends on functions of browser. You can do what you want if you assign a shortcut key to Atomic Chrome extension on brower.

**Comment by ReneFroger** [comment]
How could I assign a shortcut key to Atomic Chrome extension then? After ths, I have looked in the manual of Google Chrome, this is not mentioned by the way.

**Comment by alpha22jp** [comment]
You can find it in the settings page for extension as below.

![tmp](https://user-images.githubusercontent.com/6090562/50051577-6aad4180-0158-11e9-8945-87a23215e999.png)

**Comment by ReneFroger** [comment]
Ah, that's it! Never knew it was possible.  Perhaps it's a good idea to mention this in `README.md`?  I can imagine this might be useful for other users, given the fact Emacs is entirely keyboard-driven.


Thanks for your reply, it's working like a charm now.
