### ISSUE TITLE
Not able to install due to missing websocket package

### ISSUE THREAD

**Issue by xonev** [alpha22jp/atomic-chrome#54]
I'm trying to install `atomic-chrome` in Aquamacs 3.5 GNU Emacs 25.3.50.1.

## Steps to Reproduce
- `M-x package-install [RET] atomic-chrome [RET]`
- Expected behavior: atomic-chrome is installed
- Actual behavior: I get an error message in the minibuffer `package-install-from-archive: https://melpa.org/packages/websocket-20191123.2208.el: Not found`

**Comment by alpha22jp** [comment]
@xonev 

Maybe it was temporarily unavailable. I just checked it's available at
http://melpa.org/packages/websocket-20200419.2124.el
and I can successfully install atomic-chrome.

**Comment by xonev** [comment]
I think my local archive was out of date. I was able to install it using `M-x list-packages`.
