### ISSUE TITLE
Switching major-mode "kills" the connection

### ISSUE THREAD

**Issue by agzam** [alpha22jp/atomic-chrome#7]
When the connection between Emacs and Chrome is established, switching the major mode results in disconnect. Try for example switching from `text-mode` to `markdown-mode`.

It should be possible to switch major mode on the fly

**Comment by alpha22jp** [comment]
From the reason I wrote in #1, you can't change the major mode manually after the editing buffer is opened. Please use the customize variable `atomic-chrome-default-major-mode` and `atomic-chrome-url-major-mode-alist` instead.

**Comment by agzam** [comment]
But this is still a bug! Why would you close it? Maybe someone suggests a solution if you keep it open? This is probably the only thing that's keeping this package from being absolutely perfect.

**Comment by alpha22jp** [comment]
Hi @agzam 

Actually, I don't close the connection. But it can't send text to Chrome any more because the connection handle stored to the buffer local variable is lost.

I know this restriction can be soloved by managing connetion handles with a table instead of buffer local variable. But the solution makes the implementation a little complicated, and I don't think this is so serious problem.

**Comment by agzam** [comment]
But it is. As I noted before this package is already better than "Edit with Emacs", except this small thing.
You don't want to deal with this - fine. I am not in a position to force you onto it. I am extremely grateful already for what you have done. I'm just asking to keep the issue open, since it is a bug and it is not yet fixed. Maybe someone - more experienced in elisp than me and more motivated to fix this than you, would provide a solution. Everyone wins. No?

**Comment by alpha22jp** [comment]
Hi @agzam,

I understand. I mistook you said "why you close the *connection*?".
Okay, I'll keep the issue open.

**Comment by alpha22jp** [comment]
Hi @agzam,

I pushed some modifications which fix this issue.
Please check the latest version.

**Comment by agzam** [comment]
Oh, this is so awesome! I can now *totally* change modes and use markdown or org or whatever. Cool. I have tested it - it is slick!
